#! /bin/sh

incrementMajor(){
  VERSION="$1"
  MAJOR=$(echo "$VERSION" | cut -d. -f1)
  printf "%s.0.0" "$((MAJOR+1))"
}

hasBreakingChanges(){
  DIR="$1"
  VERSION="$2"
  cd "$DIR" || return
  if git log --oneline "$VERSION..HEAD" | grep -q "^[a-z0-9]*\\sbreak/"; then
    return 0
  fi
  return 1
}

getLastVersion(){
  DIR="$1"
  cd "$DIR" || return
  git describe --abbrev=0 2>/dev/null
}

getNextVersion() {
  DIR="$1"
  VERSION=$(getLastVersion "$DIR")
  if [ "$VERSION" = "" ]; then
    echo "0.1.0"
  else
    if hasBreakingChanges "$DIR" "$(getLastVersion "$DIR")"; then
      incrementMajor "$VERSION"
    fi
  fi
}
