#! /bin/sh
# file: semverit_test.sh

generate_base_project(){
  git init > /dev/null
  echo "change" >> README.md
  git init > /dev/null
  git add README.md > /dev/null
  git commit -m "first commit" > /dev/null
}

generate_change(){
  DIR="$1"
  (cd "$DIR" && \
  echo -n "change" >> README.md && \
  git commit -am "updating") > /dev/null
}

generate_breaking_change(){
  DIR="$1"
  (cd "$DIR" && \
  echo -n "change" >> README.md && \
  git commit -am "break/something") > /dev/null
}

tag(){
  DIR="$1"
  VERSION="$2"
  (cd "$DIR" && \
    git tag -a "$VERSION" -m "$VERSION" > /dev/null)
}

testGetNextVersion(){
  # Setup
  cd $(mktemp -d)
  DIR=$(pwd)

  generate_base_project 
  generate_change "$DIR" "$EXPECTED_VERSION" 
  tag "$DIR" "0.1.0"

  assertEquals "$EXPECTED_VERSION" "$(getNextVersion $DIR)"
}

testGetInitialVersionIfNoTagsExist(){
  EXPECTED_VERSION="0.1.0"

  cd $(mktemp -d)
  generate_base_project

  DIR=$(pwd)
  assertEquals "$EXPECTED_VERSION" "$(getNextVersion $DIR)"
}

testIncrementMajorWithBreakingChange(){
  EXISTING_VERSIONS="0.1.0"
  EXPECTED_VERSION="1.0.0"
  cd $(mktemp -d)
  DIR=$(pwd)

  generate_base_project
  generate_breaking_change "$DIR"
  tag "$DIR" "0.2.0"
  generate_breaking_change "$DIR"
  
  assertEquals "$EXPECTED_VERSION" "$(getNextVersion $DIR)"
}

testIncrementMajor(){
  EXISTING_VERSION="0.1.0"
  EXPECTED_VERSION="1.0.0"
  
  assertEquals "$EXPECTED_VERSION" $(incrementMajor $EXISTING_VERSION) 
}

testHasBreakingChanges(){
  generate_base_project

  generate_breaking_change "$DIR" "0.2.0" 
   
  DIR=$(pwd)

  if ! hasBreakingChanges "$DIR" "0.2.0"; then
    fail
  fi
}

testGetLastVersion(){
  cd $(mktemp -d)
  DIR=$(pwd)

  generate_base_project
  generate_change "$DIR"
  tag "$DIR" "0.1.0"
  generate_change "$DIR"
  tag "$DIR" "0.2.0"

  assertEquals "0.2.0" "$(getLastVersion "$DIR")"
}

oneTimeSetUp() {
  # Load include to test.
  . ./semverit
}

# Load and run shUnit2.
. ./shunit2-2.1.7/shunit2
