#! /bin/sh

incrementMajor(){
  VERSION="$1"
  MAJOR=$(echo "$VERSION" | tr -d 'v' | cut -d. -f1)
  if echo "$VERSION" | grep -q "^v"; then
    PREFIX="v"
  fi
  printf "%s%s.0.0,major\\n" "$PREFIX" "$((MAJOR+1))"
}

incrementMinor(){
  VERSION="$1"
  MAJOR=$(echo "$VERSION" | cut -d. -f1)
  MINOR=$(echo "$VERSION" | cut -d. -f2)
  printf "%s.%s.0,minor\\n" "$MAJOR" "$((MINOR+1))"
}

incrementPatch(){
  VERSION="$1"
  MAJOR=$(echo "$VERSION" | cut -d. -f1)
  MINOR=$(echo "$VERSION" | cut -d. -f2)
  PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d- -f1)
  printf "%s.%s.%s,patch\\n" "$MAJOR" "$MINOR" "$((PATCH+1))"
}

hasChange(){
  TYPE="$1"
  DIR="$2"
  VERSION="$3"
  cd "$DIR" || return
  if git log --oneline "$VERSION..HEAD" | grep -q "^[a-z0-9]*.*$TYPE/"; then
    return 0
  fi 
  return 1
}

hasBreakingChanges(){
  if hasChange "break" "$1" "$2"; then
    return 0
  fi
  return 1
}

hasFeatureChanges(){
  if hasChange "feature" "$1" "$2"; then
    return 0
  fi
  return 1
}

hasPatchChanges(){
  if hasChange "bugfix" "$1" "$2"; then
    return 0
  fi
  return 1
}

getLastVersion(){
  DIR="$1"
  cd "$DIR" || return
  # shellcheck disable=SC1117
  git tag | grep -v release | sed -r "s/([0-9]+\.[0-9]+\.[0-9]+$)/\1\.99999/"|sort -V|sed s/\.99999$// | tail -n1
}

getNextVersion() {
  DIR="$1"
  VERSION=$(getLastVersion "$DIR")
  if [ "$VERSION" = "" ]; then
    echo "0.1.0,minor"
  elif echo "$VERSION" | grep -E -q "\\-rc" ; then
    echo "$(echo "$VERSION" | cut -d- -f1),release"
  else
    if hasBreakingChanges "$DIR" "$(getLastVersion "$DIR")"; then
      incrementMajor "$VERSION"
      exit 0
    fi

    if hasFeatureChanges "$DIR"  "$(getLastVersion "$DIR")"; then
      incrementMinor "$VERSION"
      exit 0
    fi

    if hasPatchChanges "$DIR"  "$(getLastVersion "$DIR")"; then
      incrementPatch "$VERSION"
      exit 0
    fi
   
    echo "$VERSION,none" 
  fi
}
