#! /bin/sh

generate_base_project(){
  git init > /dev/null
  echo "change" >> README.md
  git init > /dev/null
  git add README.md > /dev/null
  git commit -m "first commit" > /dev/null
}

generate_change(){
  DIR="$1"
  (cd "$DIR" && \
  echo -n "change" >> README.md && \
  git commit -am "updating") > /dev/null
}

generate_breaking_change(){
  DIR="$1"
  (cd "$DIR" && \
  echo "breaking change" >> README.md && \
  git commit -am "break/something") > /dev/null
}

generate_feature_change(){
  DIR="$1"
  (cd "$DIR" && \
  echo "feature" >> README.md && \
  git commit -am "feature/something") > /dev/null
}

generate_patch_change(){
  DIR="$1"
  (cd "$DIR" && \
  echo "patch" >> README.md && \
  git commit -am "bugfix/something") > /dev/null
}

tag(){
  DIR="$1"
  VERSION="$2"
  (cd "$DIR" && \
    git tag -a "$VERSION" -m "$VERSION" > /dev/null)
}
