#! /bin/sh

incrementMajor(){
  VERSION="$1"
  MAJOR=$(echo "$VERSION" | cut -d. -f1)
  printf "%s.0.0" "$((MAJOR+1))"
}

incrementMinor(){
  VERSION="$1"
  MAJOR=$(echo "$VERSION" | cut -d. -f1)
  MINOR=$(echo "$VERSION" | cut -d. -f2)
  PATCH=$(echo "$VERSION" | cut -d. -f3)
  printf "%s.%s.%s" "$MAJOR" "$((MINOR+1))" "$PATCH"
}

hasBreakingChanges(){
  DIR="$1"
  VERSION="$2"
  cd "$DIR" || return
  if git log --oneline "$VERSION..HEAD" | grep -q "^[a-z0-9]*\\sbreak/"; then
    return 0
  fi
  return 1
}

hasFeatureChanges(){
  VERSION="$2"
  cd "$DIR" || return
  if git log --oneline "$VERSION..HEAD" | grep -q "^[a-z0-9]*\\sfeature/"; then
    return 0
  fi
  return 1
}

getLastVersion(){
  DIR="$1"
  cd "$DIR" || return
  git describe --abbrev=0 2>/dev/null
}

getNextVersion() {
  DIR="$1"
  VERSION=$(getLastVersion "$DIR")
  if [ "$VERSION" = "" ]; then
    echo "0.1.0"
  else
    if hasBreakingChanges "$DIR" "$(getLastVersion "$DIR")"; then
      incrementMajor "$VERSION"
    fi

    if hasFeatureChanges "$DIR"  "$(getLastVersion "$DIR")"; then
      incrementMinor "$VERSION"
    fi

  fi
}
